Repository podkrepi-bg/frontend, pull requests merged in 2022-03, with the labels that each got.

#527 [City] AdminLayout adjustment and CRUD
  public/locales/bg/cities.json
  public/locales/en/cities.json
  src/common/hooks/cities.ts
  src/common/routes.ts
  src/components/admin/navigation/adminMenu.tsx
  src/components/cities/CityCreatePage.tsx
  src/components/cities/CityEditPage.tsx
  src/components/cities/CityGrid.tsx
  src/components/cities/CityPage.tsx
  src/components/cities/CreateForm.tsx
  src/components/cities/EditForm.tsx
  src/components/cities/GridActions.tsx
  src/components/cities/modals/DeleteModal.tsx
  src/components/cities/modals/DeleteSelectedModal.tsx
  src/components/cities/modals/DetailsModal.tsx
  src/gql/cities.d.ts
  src/pages/admin/cities/create.tsx
  src/pages/admin/cities/edit/[id].tsx
  src/pages/admin/cities/index.tsx
  src/service/apiEndpoints.ts
  src/service/city.ts
  src/service/restRequests.ts
  src/stores/DrawerStore.ts
Labels: frontend, bootcamp

#572 Vault dashboard for admin page
  public/locales/bg/vaults.json
  public/locales/en/vaults.json
  src/common/hooks/vaults.ts
  src/common/routes.ts
  src/components/vaults/CreatePage.tsx
  src/components/vaults/EditPage.tsx
  src/components/vaults/Form.tsx
  src/components/vaults/VaultsPage.tsx
  src/components/vaults/grid/DeleteAllModal.tsx
  src/components/vaults/grid/DeleteModal.tsx
  src/components/vaults/grid/DetailsModal.tsx
  src/components/vaults/grid/Grid.tsx
  src/components/vaults/grid/GridActions.tsx
  src/components/vaults/grid/GridAppbar.tsx
  src/gql/vault.d.ts
  src/pages/admin/vaults/[id]/edit.tsx
  src/pages/admin/vaults/create.tsx
  src/pages/admin/vaults/index.tsx
  src/service/apiEndpoints.ts
  src/service/restRequests.ts
Labels: type:enhancement, frontend, bootcamp

#574 Divide restRequests into smaller files
  src/common/hooks/donations.ts
  src/components/campaigns/CampaignForm.tsx
  src/components/cities/CreateForm.tsx
  src/components/cities/EditForm.tsx
  src/components/cities/modals/DeleteModal.tsx
  src/components/contact/ContactForm.tsx
  src/components/countries/CountryForm.tsx
  src/components/countries/CountryGrid.tsx
  src/components/documents/Form.tsx
  src/components/documents/grid/DeleteAllModal.tsx
  src/components/documents/grid/DeleteModal.tsx
  src/components/support-form/SupportForm.tsx
  src/components/vaults/Form.tsx
  src/components/vaults/grid/DeleteAllModal.tsx
  src/components/vaults/grid/DeleteModal.tsx
  src/service/restRequests.ts
  src/service/restRequests/beneficiary.tsx
  src/service/restRequests/campaign.tsx
  src/service/restRequests/city.tsx
  src/service/restRequests/contact.tsx
  src/service/restRequests/country.tsx
  src/service/restRequests/document.tsx
  src/service/restRequests/donation.tsx
  src/service/restRequests/support.tsx
  src/service/restRequests/vault.tsx
Labels: frontend, bootcamp

#578 Adding select fields for ids
  public/locales/bg/beneficiary.json
  public/locales/bg/cities.json
  public/locales/bg/common.json
  public/locales/bg/vaults.json
  public/locales/en/beneficiary.json
  public/locales/en/cities.json
  public/locales/en/common.json
  public/locales/en/vaults.json
  public/maintenance.html
  public/site.webmanifest
  src/common/hooks/beneficiary.ts
  src/common/icons/Vault.tsx
  src/common/routes.ts
  src/components/admin/navigation/adminMenu.tsx
  src/components/beneficiary/Form.tsx
  src/components/beneficiary/grid/DetailsModal.tsx
  src/components/beneficiary/grid/Grid.tsx
  src/components/cities/CreateForm.tsx
  src/components/cities/EditForm.tsx
  src/components/cities/GridActions.tsx
  src/components/layout/Footer.tsx
  src/components/vaults/Form.tsx
  src/components/vaults/grid/GridActions.tsx
  src/gql/campaign-types.d.ts
  src/gql/city.d.ts
  src/gql/company.d.ts
  src/gql/search.d.ts
  src/service/apiEndpoints.ts
  src/service/beneficiary.ts
  src/service/company.ts
  src/service/coordinator.ts
  src/service/person.ts
Labels: bootcamp, admin

#596 Make home page title readable
  src/components/campaigns/CampaignDetails.tsx
  src/components/layout/Layout.tsx
Labels: bootcamp

#602 Create a layout for user profile page and implement personal info tab
  src/components/auth/profile/CertificatesTab.tsx
  src/components/auth/profile/DonationAgreementTab.tsx
  src/components/auth/profile/DonationTab.tsx
  src/components/auth/profile/PersonalInfoTab.tsx
  src/components/auth/profile/ProfilePage.tsx
  src/components/auth/profile/Tab.tsx
  src/pages/_document.tsx
Labels: bootcamp

#607 [Withdrawal] Create dashboard and CRUD functionalities
  public/locales/bg/withdrawals.json
  public/locales/en/withdrawals.json
  src/common/hooks/withdrawals.ts
  src/common/routes.ts
  src/components/admin/navigation/adminMenu.tsx
  src/components/withdrawals/CreateForm.tsx
  src/components/withdrawals/CreatePage.tsx
  src/components/withdrawals/EditForm.tsx
  src/components/withdrawals/EditPage.tsx
  src/components/withdrawals/WithdrawalPage.tsx
  src/components/withdrawals/WithdrawalTypes.ts
  src/components/withdrawals/grid/DeleteAllModal.tsx
  src/components/withdrawals/grid/DeleteModal.tsx
  src/components/withdrawals/grid/DetailsModal.tsx
  src/components/withdrawals/grid/Grid.tsx
  src/components/withdrawals/grid/GridActions.tsx
  src/components/withdrawals/grid/GridAppbar.tsx
  src/gql/withdrawals.d.ts
  src/pages/admin/withdrawals/create.tsx
  src/pages/admin/withdrawals/edit/[id].tsx
  src/pages/admin/withdrawals/index.tsx
  src/service/apiEndpoints.ts
  src/service/withdrawal.ts
Labels: frontend

#609 Removed restRequests folder and changed file extensions in service folder
  src/common/hooks/donation.ts
  src/components/campaigns/CampaignForm.tsx
  src/components/campaigns/InlineDonation.tsx
  src/components/cities/CityGrid.tsx
  src/components/cities/CreateForm.tsx
  src/components/cities/EditForm.tsx
  src/components/cities/modals/DeleteModal.tsx
  src/components/contact/ContactForm.tsx
  src/components/countries/CountryForm.tsx
  src/components/countries/CountryGrid.tsx
  src/components/documents/Form.tsx
  src/components/documents/grid/DeleteAllModal.tsx
  src/components/documents/grid/DeleteModal.tsx
  src/components/support-form/SupportForm.tsx
  src/components/vaults/Form.tsx
  src/components/vaults/grid/DeleteAllModal.tsx
  src/components/vaults/grid/DeleteModal.tsx
  src/service/campaign.ts
  src/service/city.ts
  src/service/contact.ts
  src/service/country.ts
  src/service/document.ts
  src/service/donation.ts
  src/service/restRequests/beneficiary.tsx
  src/service/restRequests/city.tsx
  src/service/support.ts
  src/service/vault.ts
Labels: bootcamp

#610 User profile donation tab
  src/common/hooks/donation.ts
  src/common/util/date.ts
  src/components/auth/profile/DonationTab.tsx
  src/gql/donations.d.ts
  src/service/apiEndpoints.ts
Labels: bootcamp

#617 Apply new design to user profile page
  src/components/auth/profile/DonationTab.tsx
  src/components/auth/profile/PersonalInfoTab.tsx
  src/components/auth/profile/ProfilePage.tsx
  src/components/auth/profile/Tab.tsx
  src/components/layout/Layout.tsx
Labels: bootcamp

#612 [Withdrawal] Create dashboard and CRUD functionalities
  src/common/hooks/withdrawals.ts
  src/components/withdrawals/CreateForm.tsx
  src/components/withdrawals/EditForm.tsx
  src/components/withdrawals/WithdrawalTypes.ts
  src/gql/withdrawals.d.ts
Labels: frontend

#622 Profile page donation certificates tab
  src/components/auth/profile/CertificatesTab.tsx
  src/components/auth/profile/DonationTab.tsx
Labels: bootcamp

#619 Fixed campaign details page
  public/locales/bg/campaigns.json
  public/locales/en/campaigns.json
  src/components/campaign-types/Form.tsx
  src/components/campaigns/CampaignDetails.tsx
  src/components/campaigns/DonorsAndDonations.tsx
  src/components/campaigns/InlineDonation.tsx
  src/service/benefactor.ts
Labels: bootcamp

#626 [Feature] Create Infographic for campaign page
  public/img/Artboard.png
  src/components/campaigns/CampaignsList.tsx
Labels: frontend

#651 Added loading image from api for campaign card and details components
  .env.local.example
  manifests/base/config-web.yaml
  manifests/base/deployment.yaml
  manifests/overlays/development/config-web.patch.yaml
  next.config.js
  src/common/util/campaignImageUrls.ts
  src/components/auth/profile/CertificatesTab.tsx
  src/components/campaigns/CampaignCard.tsx
  src/components/campaigns/CampaignDetails.tsx
  src/components/cities/grid/GridAppbar.tsx
  src/components/donations/modals/DetailsModal.tsx
  src/components/support-form/steps/ThankYou.tsx
  src/components/withdrawals/grid/DetailsModal.tsx
  src/gql/campaigns.d.ts
  src/pages/admin/donations/[id]/edit.tsx
  src/pages/admin/donations/index.tsx
Labels: bootcamp

#625 [Feature] Create campaign types filter for campaigns page
  public/locales/bg/campaigns.json
  public/locales/en/campaigns.json
  src/common/hooks/useMobile.tsx
  src/components/campaign-types/Form.tsx
  src/components/campaign-types/categories.ts
  src/components/campaigns/CampaignFilter.tsx
  src/components/campaigns/CampaignsList.tsx
  src/components/campaigns/CampaignsPage.tsx
  src/components/faq/ExpandableListItem.tsx
  src/components/faq/VerticalTabs.tsx
  src/gql/campaign-types.d.ts
  src/gql/campaigns.d.ts
  src/pages/campaigns/index.tsx
Labels: type:enhancement, frontend
