Repository podkrepi-bg/frontend, pull requests merged in 2022-02, with the labels that each got.

#512 Fix minor FE bugs (#497, #509), Add missing EN translations for campaigns
  public/locales/en/campaigns.json
  src/components/common/BankTransfer.tsx
  src/components/support-form/SupportForm.tsx
Labels: bug, frontend

#524 Document entity
  package.json
  public/locales/bg/documents.json
  public/locales/en/documents.json
  src/common/hooks/documents.ts
  src/common/routes.ts
  src/components/admin/navigation/AdminLayout.tsx
  src/components/admin/navigation/adminMenu.tsx
  src/components/documents/CreatePage.tsx
  src/components/documents/DocumentsPage.tsx
  src/components/documents/EditPage.tsx
  src/components/documents/Form.tsx
  src/components/documents/grid/DeleteAllModal.tsx
  src/components/documents/grid/DeleteModal.tsx
  src/components/documents/grid/DetailsModal.tsx
  src/components/documents/grid/Grid.tsx
  src/components/documents/grid/GridActions.tsx
  src/components/documents/grid/GridAppbar.tsx
  src/gql/document.d.ts
  src/pages/admin/documents/[id]/edit.tsx
  src/pages/admin/documents/create.tsx
  src/pages/admin/documents/index.tsx
  src/service/apiEndpoints.ts
  src/service/restRequests.ts
  src/stores/documents/ModalStore.ts
  yarn.lock
Labels: type:enhancement, frontend

#502 Crud for country entity (frontend)
  public/locales/bg/countries.json
  public/locales/en/countries.json
  src/common/hooks/countries.ts
  src/common/routes.ts
  src/components/admin/navigation/adminMenu.tsx
  src/components/countries/ActionButtons.tsx
  src/components/countries/CountriesPage.tsx
  src/components/countries/CountryCreatePage.tsx
  src/components/countries/CountryEditPage.tsx
  src/components/countries/CountryForm.tsx
  src/components/countries/CountryGrid.tsx
  src/components/countries/DeleteRowDialog.tsx
  src/components/countries/DeleteRowsDialog.tsx
  src/components/countries/HeadingSeparator.tsx
  src/components/countries/InfoDialog.tsx
  src/gql/countries.d.ts
  src/pages/admin/countries/[id]/index.tsx
  src/pages/admin/countries/create.tsx
  src/pages/admin/countries/index.tsx
  src/service/apiEndpoints.ts
  src/service/restRequests.ts
Labels: frontend, bootcamp

#558 Change menu dropdown links color
  src/components/layout/nav/DevelopmentMenu.tsx
  src/components/layout/nav/DonationMenu.tsx
  src/components/layout/nav/ProjectMenu.tsx
Labels: frontend

#559 Update copyright text, change profile dropdown color links
  public/locales/bg/common.json
  public/locales/en/common.json
  src/components/layout/nav/PublicMenu.tsx
Labels: frontend

#530 added missing link for coordinators to admin
  src/components/admin/navigation/adminMenu.tsx
Labels: frontend, bootcamp
