Repository podkrepi-bg/frontend, pull requests merged in 2022-11, with the labels that each got.

#1121 Fix visual issue with Menu items in the MainNav
  src/components/layout/nav/DevelopmentMenu.tsx
  src/components/layout/nav/DonationMenu.tsx
  src/components/layout/nav/GenericNavMenu.tsx
  src/components/layout/nav/ProjectMenu.tsx
Labels: bug

#1138 [Feature] Add search to the FAQ page
  README.md
  public/locales/bg/faq.json
  public/locales/en/faq.json
  src/components/faq/FaqPage.tsx
  src/components/faq/FaqSearch.tsx
  src/components/faq/OnHold.tsx
  src/components/faq/VerticalTabs.tsx
  src/components/faq/contents/faq-categories.enum.ts
  src/components/faq/helpers/filters.ts
  src/components/faq/helpers/utils.ts
  src/pages/faq/[section].tsx
  src/pages/faq/index.tsx
Labels: type:enhancement

#1207 Update 'See more' buttons on About us page
  src/components/about/AboutPage.styled.tsx
  src/components/about/sections/ManagementBoardSection/ManagementBoardDescription.tsx
  src/components/about/sections/ManagementBoardSection/ManagementBoardSection.tsx
  src/components/about/sections/ManagementBoardSection/ManagementBoardsection.styled.tsx
  src/components/about/sections/ManagementBoardSection/TeamMemberDescription.tsx
Labels: frontend, ui
