Repository podkrepi-bg/frontend, pull requests merged in 2022-05, with the labels that each got.

#746 Added background to pdf
  README.md
  public/img/pdf/background.png
  public/img/pdf/sign.png
  public/img/pdf/sign1.png
  public/img/pdf/thank-you.png
  src/components/pdf/Certificate.tsx
Labels: bootcamp

#754 Improved donation certificate deisgn
  public/fonts/Arial.ttf
  src/components/pdf/Certificate.tsx
  src/components/pdf/Logo.tsx
Labels: bootcamp

#761 Add button hover states in the theme to correspond to the UI theme
  .env.local.example
  src/common/theme.ts
  src/components/campaigns/CampaignCard.tsx
  src/components/campaigns/CampaignForm.tsx
  src/components/campaigns/DonorsAndDonations.tsx
  src/components/campaigns/InlineDonation.tsx
  src/components/index/sections/CampaignsSection.tsx
  src/components/index/sections/FaqSection.tsx
  src/components/index/sections/ReadyToStartCampaignSection.tsx
  src/components/index/sections/WantToHelpPodkrepiBg.tsx
  src/components/layout/nav/PrivateMenu.tsx
  src/components/layout/nav/PublicMenu.tsx
Labels: frontend, ui

#757 Feature/660 one time donation flow
  .env.local.example
  public/locales/bg/common.json
  public/locales/bg/one-time-donation.json
  public/locales/en/common.json
  public/locales/en/one-time-donation.json
  src/common/icons/Fail.tsx
  src/common/icons/Google.tsx
  src/common/icons/Success.tsx
  src/common/routes.ts
  src/common/theme.ts
  src/common/util/money.ts
  src/common/util/useCurrentPerson.ts
  src/components/campaigns/CampaignCard.tsx
  src/components/campaigns/InlineDonation.tsx
  src/components/common/CopyTextButton.tsx
  src/components/common/ExternalLinkButton.tsx
  src/components/common/form/CircleCheckboxField.tsx
  src/components/common/form/RadioButton.tsx
  src/components/common/form/RadioButtonGroup.tsx
  src/components/one-time-donation/AnonymousForm.tsx
  src/components/one-time-donation/FormikStepper.tsx
  src/components/one-time-donation/LoginForm.tsx
  src/components/one-time-donation/OneTimeDonationPage.tsx
  src/components/one-time-donation/Steps.tsx
  src/components/one-time-donation/helpers/stepperContext.ts
  src/components/one-time-donation/helpers/validation-schema.ts
  src/components/one-time-donation/steps/Fail.tsx
  src/components/one-time-donation/steps/FirstStep.tsx
  src/components/one-time-donation/steps/SecondStep.tsx
  src/components/one-time-donation/steps/Success.tsx
  src/components/one-time-donation/steps/ThirdStep.tsx
  src/gql/donations.d.ts
  src/middleware/auth/keycloak.ts
  src/pages/campaigns/donation/[slug].tsx
  src/service/apiEndpoints.ts
  src/service/donation.ts
Labels: frontend
