Repository podkrepi-bg/frontend, pull requests merged in 2022-04, with the labels that each got.

#656 Upload files with types
  src/components/campaign-file/roles.ts
  src/components/campaigns/CampaignForm.tsx
  src/components/campaigns/grid/CreateForm.tsx
  src/components/file-upload/FileList.tsx
  src/service/campaign.ts
Labels: bootcamp

#662 [expense] Created admin dashboard panel
  public/locales/bg/common.json
  public/locales/bg/expenses.json
  public/locales/en/common.json
  public/locales/en/expenses.json
  src/common/hooks/expenses.ts
  src/common/routes.ts
  src/components/admin/DetailsDialog.tsx
  src/components/admin/navigation/adminMenu.tsx
  src/components/currency/CurrencySelect.tsx
  src/components/expenses/DeletedCheckbox.tsx
  src/components/expenses/DocumentSelect.tsx
  src/components/expenses/ExpenseStatusSelect.tsx
  src/components/expenses/ExpenseTypeSelect.tsx
  src/components/expenses/ExpensesCreatePage.tsx
  src/components/expenses/ExpensesEditPage.tsx
  src/components/expenses/ExpensesPage.tsx
  src/components/expenses/Form.tsx
  src/components/expenses/PersonSelect.tsx
  src/components/expenses/VaultSelect.tsx
  src/components/expenses/grid/DeleteModal.tsx
  src/components/expenses/grid/DetailsModal.tsx
  src/components/expenses/grid/Grid.tsx
  src/components/expenses/grid/GridAppbar.tsx
  src/components/expenses/grid/GridHelper.tsx
  src/gql/expenses.ts
  src/pages/admin/expenses/[id]/index.tsx
  src/pages/admin/expenses/create.tsx
  src/pages/admin/expenses/index.tsx
  src/service/apiEndpoints.ts
  src/service/expense.ts
Labels: type:enhancement, frontend, bootcamp, admin

#669 Reuse CurrencySelect
  src/components/vaults/Form.tsx
  src/components/withdrawals/CreateForm.tsx
  src/components/withdrawals/EditForm.tsx
Labels: bootcamp, admin

#670 Added functionality for adding files when editing a campaign
  src/components/campaigns/grid/CreateForm.tsx
  src/components/campaigns/grid/EditForm.tsx
  src/components/file-upload/FileList.tsx
Labels: bootcamp

#685 Change date format from MM/dd/yyyy to dd/MM/yyyy in user profile
  src/components/auth/profile/DonationTab.tsx
Labels: frontend

#688 Redirect user to same page before login page
  src/components/auth/login/LoginPage.tsx
Labels: frontend

#687 User can edit name and birthday from profile page
  public/locales/bg/common.json
  public/locales/en/common.json
  src/common/util/date.ts
  src/common/util/useCurrentPerson.ts
  src/components/auth/profile/PersonalInfoTab.tsx
  src/components/auth/profile/UpdateBirthdayModal.tsx
  src/components/auth/profile/UpdateNameModal.tsx
  src/gql/person.d.ts
  src/service/apiEndpoints.ts
Labels: frontend, bootcamp

#702 Redirect user to keycloak to change password
  src/components/auth/profile/PersonalInfoTab.tsx
Labels: frontend

#711 Add description of how to start the stripe cli
  README.md
Labels: type:documentation

#709 Add getting campaign donations from backend
  public/locales/bg/campaigns.json
  public/locales/en/campaigns.json
  src/common/hooks/campaigns.ts
  src/common/util/date.ts
  src/components/campaigns/DonorsAndDonations.tsx
  src/components/campaigns/InlineDonation.tsx
  src/gql/campaigns.ts
  src/service/apiEndpoints.ts
Labels: frontend, domain:campaigns

#714 user to be redirected to a new page with info about FAQ on mobile device
  src/components/layout/nav/DonationMenuMobile.tsx
Labels: frontend, bootcamp, admin
