Repository podkrepi-bg/frontend, pull requests merged in 2023-01, with the labels that each got.

#1274 `RadioAccordionGroup` element for the new donation flow
  src/components/donation-flow/BankIcon.tsx
  src/components/donation-flow/CardIcon.tsx
  src/components/donation-flow/RadioAccordionGroup.tsx
  src/components/donation-flow/stripe/PaymentDetailsStripeForm.tsx
  src/components/one-time-donation/OneTimeDonationPage.tsx
  src/stores/UserStore.ts
Labels: area: donations

#1300 avatar-letters-hotfix - add a fallback to `given_name` and `family_name`
  src/components/layout/nav/PrivateMenu.tsx
Labels: run tests

#1304 put campaigns with status different than active at the bottom of the …
  src/common/hooks/campaigns.ts
  src/components/campaigns/CampaignFilter.tsx
  src/components/index/sections/CampaignsSection/CampaignsSection.tsx
  src/pages/campaigns/index.tsx
  src/pages/index.tsx
Labels: type: business priority

#1303 Fix Campaigns section max width and alignment on Homepage and Campaigns page
  src/components/campaigns/CampaignsList.tsx
  src/components/campaigns/CampaignsPage.tsx
  src/components/index/sections/CampaignsSection/CampaignsSection.styled.tsx
Labels: area: frontend

#1306 Fix the header on Campaigns listing page
  src/components/campaigns/CampaignsPage.tsx
Labels: area: frontend

#1294 New Donation Flow - Authentication form
  src/components/donation-flow/DonationFlowForm.tsx
  src/components/donation-flow/DonationFlowPage.tsx
  src/components/donation-flow/common/RadioAccordionGroup.tsx
  src/components/donation-flow/common/RadioCardGroup.tsx
  src/components/donation-flow/helpers/stripe-fee-calculator.ts
  src/components/donation-flow/steps/Amount.tsx
  src/components/donation-flow/steps/PaymentMethod.tsx
  src/components/donation-flow/steps/authentication/Authentication.tsx
  src/components/donation-flow/steps/authentication/InlineLoginForm.tsx
  src/components/donation-flow/steps/authentication/InlineRegisterForm.tsx
  src/components/donation-flow/steps/payment-method/PaymentDetailsStripeForm.tsx
  src/components/donation-flow/steps/payment-method/PaymentMethod.tsx
  src/components/donation-flow/steps/payment-method/TaxesCheckbox.tsx
  src/service/apiEndpoints.ts
  yarn.lock
Labels: area: donations

#1265 #1188, #1194 - Add POM for the E2E tests and update all tests
  .github/workflows/playwright.yml
  .gitignore
  e2e/AuthPage.ts
  e2e/README.md
  e2e/data/enums/donation-regions.enum.ts
  e2e/data/enums/languages.enum.ts
  e2e/data/localization.ts
  e2e/data/support-page-tests.data.ts
  e2e/local/campaigns.spec.ts
  e2e/local/donation.spec.ts
  e2e/local/homepage.spec.ts
  e2e/local/support.spec.ts
  e2e/package.json
  e2e/pages/web-pages/admin/AuthPage.ts
  e2e/pages/web-pages/base.page.ts
  e2e/pages/web-pages/campaigns/campaigns.page.ts
  e2e/pages/web-pages/campaigns/donation.page.ts
  e2e/pages/web-pages/external/stripe-checkout.page.ts
  e2e/pages/web-pages/header.page.ts
  e2e/pages/web-pages/home.page.ts
  e2e/pages/web-pages/support.page.ts
  e2e/playwright.config.ts
  e2e/staging/anon-donation-custom.spec.ts
  e2e/staging/anon-donation-fixed.spec.ts
  e2e/staging/homepage.spec.ts
  e2e/tests/regression/donation-flow/anon-donation-custom.spec.ts
  e2e/tests/regression/donation-flow/anon-donation-fixed.spec.ts
  e2e/tests/regression/support-as-member.spec.ts
  e2e/tests/smoke/smoke-campaigns.spec.ts
  e2e/tests/smoke/smoke-homepage.spec.ts
  e2e/utils/helpers.ts
  e2e/utils/types.ts
  e2e/yarn.lock
  next.config.js
  package.json
  playwright.config.ts
  public/locales/bg/common.json
  public/locales/en/common.json
  src/components/campaigns/CampaignCard.tsx
  src/components/campaigns/CampaignsList.tsx
  src/components/index/sections/CampaignsSection/CampaignsSection.tsx
  src/components/index/sections/Jumbotron/Jumbotron.tsx
  src/components/layout/nav/MainNavMenu.tsx
  src/components/layout/nav/MobileNav/MobileNav.tsx
  tsconfig.build.json
  yarn.lock
Labels: type: enhancement, area: e2e tests, run tests

#1307 Update campaign donation component
  public/locales/bg/campaigns.json
  public/locales/bg/common.json
  public/locales/en/campaigns.json
  public/locales/en/common.json
  src/common/util/money.ts
  src/components/campaigns/DonationWishes.tsx
  src/components/campaigns/DonorsAndDonations.tsx
  src/components/campaigns/InlineDonation.tsx
  src/components/campaigns/ViewCampaignPage.tsx
Labels: area: frontend
