Repository podkrepi-bg/frontend, pull requests merged in 2023-02, with the labels that each got.

#1314 New Donation Flow - Alerts and Summary Column
  src/components/common/ConfirmationDialog.tsx
  src/components/common/form/RadioButtonGroup.tsx
  src/components/donation-flow/DonationFlowContext.tsx
  src/components/donation-flow/DonationFlowForm.tsx
  src/components/donation-flow/StripeElementsProvider.tsx
  src/components/donation-flow/alerts/AlertsColumn.tsx
  src/components/donation-flow/alerts/AlertsContent.tsx
  src/components/donation-flow/alerts/AnchoredAlert.tsx
  src/components/donation-flow/alerts/PaymentSummaryAlert.tsx
  src/components/donation-flow/common/StepSplitter.tsx
  src/components/donation-flow/helpers/types.ts
  src/components/donation-flow/steps/Amount.tsx
  src/components/donation-flow/steps/authentication/Authentication.tsx
  src/components/donation-flow/steps/authentication/InlineLoginForm.tsx
  src/components/donation-flow/steps/authentication/InlineRegisterForm.tsx
  src/components/donation-flow/steps/payment-method/PaymentMethod.tsx
  src/components/donation-flow/steps/payment-method/TaxesCheckbox.tsx
  src/gql/donations.d.ts
  src/service/donation.ts
Labels: type: RFC, area: donations

#1319 Update money representation
  src/common/util/money.ts
Labels: area: frontend

#1323 Fix - e2e `checkURL` tests failing unexpectedly
  .github/workflows/build-nextjs.yml
  .github/workflows/lint.yml
  .github/workflows/playwright.yml
  e2e/pages/web-pages/campaigns/campaigns.page.ts
  e2e/pages/web-pages/campaigns/donation.page.ts
  e2e/pages/web-pages/support.page.ts
  e2e/tests/regression/support-as-member.spec.ts
  src/components/one-time-donation/steps/FirstStep.tsx
Labels: type: bug, area: e2e tests

#1322 New Donation Flow - #1297 #1291 Bank Transfer flow and Success page
  e2e/pages/web-pages/campaigns/donation-old.page.ts
  e2e/tests/regression/donation-flow/anon-donation-custom.spec.ts
  e2e/tests/regression/donation-flow/anon-donation-fixed.spec.ts
  e2e/tests/smoke/smoke-campaigns.spec.ts
  next.config.js
  src/common/routes.ts
  src/components/common/SocialShareListButton.tsx
  src/components/common/form/RadioButton.tsx
  src/components/common/form/RadioButtonGroup.tsx
  src/components/donation-flow/DonationFlowContext.tsx
  src/components/donation-flow/DonationFlowForm.tsx
  src/components/donation-flow/DonationFlowLayout.tsx
  src/components/donation-flow/DonationFlowPage.tsx
  src/components/donation-flow/DonationFlowStatusPage.tsx
  src/components/donation-flow/alerts/AlertsColumn.tsx
  src/components/donation-flow/alerts/PaymentSummaryAlert.tsx
  src/components/donation-flow/contexts/DonationFlowProvider.tsx
  src/components/donation-flow/contexts/StripeElementsProvider.tsx
  src/components/donation-flow/helpers/types.ts
  src/components/donation-flow/icons/SuccessGraphic.tsx
  src/components/donation-flow/steps/Amount.tsx
  src/components/donation-flow/steps/authentication/Authentication.tsx
  src/components/donation-flow/steps/authentication/InlineLoginForm.tsx
  src/components/donation-flow/steps/authentication/InlineRegisterForm.tsx
  src/components/donation-flow/steps/payment-method/BankPayment.tsx
  src/components/donation-flow/steps/payment-method/PaymentMethod.tsx
  src/pages/campaigns/donation-old/[slug].tsx
  src/pages/campaigns/donation/[slug]/index.tsx
  src/pages/campaigns/donation/[slug]/status.tsx
  src/service/donation.ts
  src/service/stripeClient.ts
Labels: area: donations

#1334 New Donation Flow - Translations
  e2e/pages/web-pages/base.page.ts
  public/locales/bg/common.json
  public/locales/bg/donation-flow.json
  public/locales/en/common.json
  public/locales/en/donation-flow.json
  src/components/common/SocialShareListButton.tsx
  src/components/common/form/CheckboxField.tsx
  src/components/donation-flow/DonationFlowForm.tsx
  src/components/donation-flow/DonationFlowStatusPage.tsx
  src/components/donation-flow/alerts/AlertsColumn.tsx
  src/components/donation-flow/alerts/AlertsContent.tsx
  src/components/donation-flow/alerts/PaymentSummaryAlert.tsx
  src/components/donation-flow/steps/Amount.tsx
  src/components/donation-flow/steps/authentication/Authentication.tsx
  src/components/donation-flow/steps/authentication/InlineLoginForm.tsx
  src/components/donation-flow/steps/authentication/InlineRegisterForm.tsx
  src/components/donation-flow/steps/payment-method/BankPayment.tsx
  src/components/donation-flow/steps/payment-method/PaymentMethod.tsx
  src/components/donation-flow/steps/payment-method/TaxesCheckbox.tsx
  src/pages/campaigns/donation/[slug]/index.tsx
  src/pages/campaigns/donation/[slug]/status.tsx
Labels: area: i18n, area: donations

#1338 Display avatars on campaign details page on local environment
  src/common/util/campaignImageUrls.ts
Labels: area: frontend

#1326 Update FE of Campaign Details page according to the new design
  public/img/approval-icon.png
  public/img/donation-icon.png
  public/img/transparency-icon.png
  public/locales/bg/campaigns.json
  public/locales/bg/irregularity.json
  public/locales/en/campaigns.json
  public/locales/en/irregularity.json
  src/components/campaigns/CampaignDetails.tsx
  src/components/campaigns/CampaignInfo.tsx
  src/components/campaigns/CampaignInfoGraphics.tsx
  src/components/campaigns/CampaignInfoOperator.tsx
  src/components/campaigns/CampaignInfoOrganizer.tsx
  src/components/campaigns/IrregularityReport.tsx
  src/components/campaigns/ViewCampaignPage.tsx
Labels: area: frontend, run tests

#1339 Increase number of donations in Donation component
  src/components/campaigns/DonorsAndDonations.tsx
Labels: area: frontend

#1347 Update infographics on Homepage
  public/infographic-bg.svg
  src/components/index/sections/HowWeWorkSection/HowWeWorkSection.styled.tsx
  src/components/index/sections/HowWeWorkSection/HowWeWorkSection.tsx
Labels: area: frontend

#1346 common/LinkButton.tsx: Manage tabIndex property correctly
  src/components/common/LinkButton.tsx
Labels: area: a11y

#1355 Update Donation Messages styles
  src/components/campaigns/CampaignDetails.tsx
  src/components/campaigns/CampaignInfoGraphics.tsx
  src/components/campaigns/DonationWishes.tsx
Labels: area: frontend

#1365 Update Active team members on About page
  public/img/team-photos/AndreyPetrov.png
  public/img/team-photos/ChavdarChenkov.png
  public/img/team-photos/HristiyanHristov.png
  public/img/team-photos/JanetaDimitrova.png
  public/img/team-photos/LianaZafiri.png
  public/img/team-photos/NeliTancheva.png
  public/img/team-photos/SlavchoIvanov.png
  public/img/team-photos/YanitaYurukova.png
  src/components/about/helpers/activeMembersData.tsx
Labels: area: frontend

#1370 Add minor responsive UI fixes on Campaign details page
  src/components/client/campaigns/CampaignDetails.tsx
  src/components/client/campaigns/InlineDonation.tsx
Labels: area: frontend, run tests
