Repository podkrepi-bg/frontend, pull requests merged in 2023-07, with the labels that each got.

#1466 Add UI fixes on campaign cards on Homepage
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx
Labels: area: frontend

#1468 Revert "temporary switched off donation notification popups"
  src/pages/_app.tsx
Labels: run tests

#1482 Implement Partners section, update Media section
  public/locales/bg/index.json
  public/locales/en/index.json
  src/common/routes.ts
  src/components/admin/partners/helpers/partnersData.ts
  src/components/client/index/IndexPage.tsx
  src/components/client/index/sections/MediaSection/MediaSection.styled.tsx
  src/components/client/index/sections/PartnersSection/PartnersSection.styled.tsx
  src/components/client/index/sections/PartnersSection/PartnersSection.tsx
Labels: area: frontend

#1491 Added new UI updates on campaign cards on Homepage
  public/locales/bg/campaigns.json
  public/locales/en/campaigns.json
  public/locales/en/common.json
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.styled.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.tsx
Labels: area: frontend

#1502 Open Partners' websites and Articles in new tabs
  src/components/client/index/sections/MediaSection/MediaSection.styled.tsx
  src/components/client/index/sections/PartnersSection/PartnersSection.styled.tsx
Labels: area: frontend

#1500 Add UI updates on Campaign cards and Inline Donation component
  package.json
  public/locales/bg/campaigns.json
  public/locales/en/campaigns.json
  src/components/client/campaigns/CampaignCard.tsx
  src/components/client/campaigns/CampaignProgress.tsx
  src/components/client/campaigns/CampaignsPage.tsx
  src/components/client/campaigns/InlineDonation.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignsSection.styled.tsx
  yarn.lock
Labels: area: frontend

#1507 Update Progress bar's percentage
  src/components/client/campaigns/CampaignProgress.tsx
Labels: area: frontend

#1521 Update cards on campaigns page
  e2e/pages/web-pages/campaigns/campaigns.page.ts
  public/locales/bg/campaigns.json
  src/components/client/campaigns/CampaignCard.tsx
  src/components/client/campaigns/CampaignCard/CampaignCard.styled.tsx
  src/components/client/campaigns/CampaignCard/CampaignCard.tsx
  src/components/client/campaigns/CampaignsList.tsx
  src/components/client/campaigns/SuccessfullCampaignTag.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
Labels: area: frontend

#1526 Update Donate button state on campaign card
  src/components/client/campaigns/CampaignCard/CampaignCard.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
Labels: area: frontend, area: campaigns
