Repository podkrepi-bg/frontend, pull requests merged in 2024-03, with the labels that each got.

#1731 pages/campaigns: Optimizations and improvements
  src/components/client/campaigns/CampaignFilter.tsx
  src/components/client/campaigns/CampaignsList.tsx
  src/components/client/campaigns/CampaignsPage.tsx
  src/components/client/index/sections/ActiveCampaignsSection/ActiveCampaignCard/ActiveCampaignCard.styled.tsx
  src/pages/campaigns/index.tsx
Labels: run tests

#1737 add help us improve field to all registrations
  public/locales/bg/validation.json
  public/locales/en/validation.json
  src/components/client/auth/register/CorporateRegisterForm.tsx
  src/components/client/auth/register/RegisterForm.tsx
  src/components/common/form/HelpUsImproveField.tsx
  src/gql/user-registration.ts
Labels: area: frontend, run tests

#1745 fix: Indent scan_manifest job correctly in yaml files
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: run tests

#1743 Temporarily hide Attract donators and Corporate partnership tabs from FAQ page
  src/components/client/faq/FaqPage.tsx
Labels: area: frontend, run tests

#1744 Unify fontSize values using pxToRem from the theme
  src/components/admin/affiliates/AffiliatesPage.tsx
  src/components/admin/countries/grid/CountryGrid.tsx
  src/components/admin/expenses/grid/Grid.tsx
  src/components/client/auth/profile/AffiliateProgramTab.tsx
  src/components/client/auth/profile/CertificatesTab.tsx
  src/components/client/auth/profile/DonationAgreementTab.tsx
  src/components/client/auth/profile/DonationTab.tsx
  src/components/client/auth/profile/MyCampaignsTab.tsx
  src/components/client/auth/profile/MyNotificationsTab.tsx
  src/components/client/auth/profile/PersonalInfoTab.tsx
  src/components/client/auth/profile/ProfilePage.tsx
  src/components/client/auth/register/RegisterPage.tsx
  src/components/client/campaign-expenses/grid/CampaignExpensesGrid.tsx
  src/components/client/campaign-news/secured/NewsAdminPage.tsx
  src/components/client/campaigns/CampaignDetails.tsx
  src/components/client/campaigns/CampaignsPage.tsx
  src/components/client/campaigns/DonationWishes.tsx
  src/components/client/campaigns/InlineDonation.tsx
  src/components/client/irregularity/helpers/Remark.tsx
  src/components/client/irregularity/steps/Info.tsx
  src/components/client/layout/nav/AdminMenu.tsx
  src/components/client/layout/nav/AuthLinks/AuthLinks.styled.tsx
  src/components/client/layout/nav/PrivateMenu.tsx
  src/components/client/notifications/CampaignSubscribeModal.tsx
  src/components/client/notifications/GeneralSubscribeModal.tsx
  src/components/client/notifications/SubscriptionPage.tsx
  src/components/common/FormFieldButton.tsx
  src/components/common/QuillStyleWrapper.tsx
  src/components/common/navigation/AppBarMenu.tsx
  src/gql/campaigns.ts
Labels: run tests

#1742 Update Partners page and Partners section on Homepage
  public/img/partners/allChannels.svg
  public/img/partners/brainDonors.svg
  public/img/partners/crossRoads.svg
  public/img/partners/darik.svg
  public/img/partners/eightyEight.svg
  public/img/partners/estProduction.svg
  public/img/partners/ideaComm.svg
  public/img/partners/irisSolutions.svg
  public/img/partners/kotaOne.svg
  public/img/partners/mentormate.svg
  public/img/partners/softuni.svg
  public/img/partners/superhosting.svg
  public/img/partners/tv1.svg
  public/locales/bg/partners.json
  public/locales/en/partners.json
  src/common/routes.ts
  src/components/admin/partners/Partners.styled.tsx
  src/components/admin/partners/PartnersContent.tsx
  src/components/admin/partners/helpers/partnersData.ts
Labels: area: frontend

#1751 Update checkbox text on Register form
  public/locales/bg/validation.json
  public/locales/en/validation.json
Labels: area: i18n

#1755 Fix EN translation misspelling
  public/locales/en/common.json
Labels: area: i18n, run tests
